import type { IntakeSchema } from "./types";

export const intakeSchema: IntakeSchema = {
  schemaId: "website-intake-v1",
  version: "1.0.0",
  status: "active",
  sections: [
    {
      id: "business",
      title: "Business overview",
      description: "Capture the core context for the site and the people behind it.",
      order: 1,
      alwaysShown: true,
    },
    {
      id: "goals",
      title: "Project goals",
      description: "What success looks like and how the project will be judged.",
      order: 2,
      alwaysShown: true,
    },
    {
      id: "existing_site",
      title: "Existing website",
      description: "Only shown for redesign and migration projects.",
      order: 3,
      visibleWhen: { op: "or", rules: [{ op: "equals", field: "websiteType", value: "redesign" }, { op: "equals", field: "websiteType", value: "migration" }] },
    },
    {
      id: "audience",
      title: "Audience and messaging",
      description: "Who the site serves and what they need to understand quickly.",
      order: 4,
      alwaysShown: true,
    },
    {
      id: "content",
      title: "Pages and content",
      description: "Structure, sitemap and content readiness.",
      order: 5,
      alwaysShown: true,
    },
    {
      id: "features",
      title: "Features",
      description: "Core interactions required for the build.",
      order: 6,
      alwaysShown: true,
    },
    {
      id: "booking",
      title: "Booking",
      description: "Scheduling and calendar workflow details.",
      order: 7,
      visibleWhen: { op: "equals", field: "bookingRequired", value: "yes" },
    },
    {
      id: "payments",
      title: "Payments",
      description: "Commerce, refunds and transaction requirements.",
      order: 8,
      visibleWhen: { op: "equals", field: "paymentsRequired", value: "yes" },
    },
    {
      id: "portal",
      title: "Portal and access",
      description: "Membership, login and role based access details.",
      order: 9,
      visibleWhen: { op: "equals", field: "portalRequired", value: "yes" },
    },
    {
      id: "integrations",
      title: "Integrations",
      description: "Systems and services that must connect to the website.",
      order: 10,
      alwaysShown: true,
    },
    {
      id: "seo",
      title: "SEO and analytics",
      description: "Search, migration and measurement details.",
      order: 11,
      alwaysShown: true,
      visibleWhen: { op: "or", rules: [{ op: "equals", field: "websiteType", value: "redesign" }, { op: "equals", field: "websiteType", value: "migration" }, { op: "equals", field: "seoImportant", value: "yes" }] },
    },
    {
      id: "compliance",
      title: "Compliance",
      description: "Accessibility, privacy and regulatory requirements.",
      order: 12,
      alwaysShown: true,
    },
    {
      id: "timeline",
      title: "Timeline and budget",
      description: "Delivery expectations and commercial constraints.",
      order: 13,
      alwaysShown: true,
    },
    {
      id: "maintenance",
      title: "Maintenance",
      description: "Who maintains the site after launch.",
      order: 14,
      alwaysShown: true,
    },
    {
      id: "review",
      title: "Review",
      description: "Confirm the intake before submission.",
      order: 15,
      alwaysShown: true,
    },
  ],
  questions: [
    {
      id: "clientName",
      sectionId: "business",
      label: "Client name",
      type: "text",
      required: true,
      placeholder: "Acme Studio",
      prdMapping: ["cover.client"],
      riskCategory: "contact",
      validation: { minLength: 2, maxLength: 120 },
    },
    {
      id: "projectName",
      sectionId: "business",
      label: "Project name",
      type: "text",
      required: true,
      placeholder: "Website refresh",
      prdMapping: ["cover.project"],
      riskCategory: "project",
    },
    {
      id: "contactEmail",
      sectionId: "business",
      label: "Primary contact email",
      type: "email",
      required: true,
      placeholder: "owner@example.com",
      prdMapping: ["cover.contact"],
    },
    {
      id: "websiteType",
      sectionId: "business",
      label: "What best describes this project?",
      type: "radio",
      required: true,
      options: [
        { label: "New website", value: "new_website" },
        { label: "Redesign", value: "redesign" },
        { label: "Migration", value: "migration" },
      ],
      prdMapping: ["scope.type"],
    },
    {
      id: "businessGoal",
      sectionId: "goals",
      label: "Primary business goal",
      type: "textarea",
      required: true,
      placeholder: "Increase qualified lead volume from the website.",
      prdMapping: ["goals.primary"],
    },
    {
      id: "successMetric",
      sectionId: "goals",
      label: "How will success be measured?",
      type: "textarea",
      required: true,
      placeholder: "Bookings, leads, conversion rate, revenue or a mix.",
      prdMapping: ["goals.success_metrics"],
    },
    {
      id: "currentUrl",
      sectionId: "existing_site",
      label: "Current website URL",
      type: "url",
      requiredWhen: { op: "or", rules: [{ op: "equals", field: "websiteType", value: "redesign" }, { op: "equals", field: "websiteType", value: "migration" }] },
      visibleWhen: { op: "or", rules: [{ op: "equals", field: "websiteType", value: "redesign" }, { op: "equals", field: "websiteType", value: "migration" }] },
      hiddenAnswerPolicy: "retain_for_audit",
      prdMapping: ["existing.url"],
    },
    {
      id: "currentPainPoints",
      sectionId: "existing_site",
      label: "Current website pain points",
      type: "textarea",
      requiredWhen: { op: "or", rules: [{ op: "equals", field: "websiteType", value: "redesign" }, { op: "equals", field: "websiteType", value: "migration" }] },
      visibleWhen: { op: "or", rules: [{ op: "equals", field: "websiteType", value: "redesign" }, { op: "equals", field: "websiteType", value: "migration" }] },
      hiddenAnswerPolicy: "retain_when_hidden",
      prdMapping: ["existing.pain_points"],
    },
    {
      id: "targetAudience",
      sectionId: "audience",
      label: "Target audience",
      type: "textarea",
      required: true,
      placeholder: "Who the site serves and what they care about.",
      prdMapping: ["audience.primary"],
    },
    {
      id: "keyDifferentiator",
      sectionId: "audience",
      label: "Primary differentiator",
      type: "text",
      required: true,
      placeholder: "Why people should choose you.",
      prdMapping: ["audience.value_prop"],
    },
    {
      id: "pagesNeeded",
      sectionId: "content",
      label: "Key pages needed",
      type: "textarea",
      required: true,
      placeholder: "Home, services, about, contact, FAQ...",
      prdMapping: ["content.pages"],
    },
    {
      id: "contentReady",
      sectionId: "content",
      label: "Is content ready?",
      type: "select",
      required: true,
      options: [
        { label: "Yes", value: "yes" },
        { label: "No", value: "no" },
        { label: "Partial", value: "partial" },
      ],
      prdMapping: ["content.readiness"],
      riskCategory: "content",
    },
    {
      id: "formsRequired",
      sectionId: "features",
      label: "Do you need forms?",
      type: "select",
      required: true,
      options: [
        { label: "Yes", value: "yes" },
        { label: "No", value: "no" },
      ],
      prdMapping: ["features.forms"],
    },
    {
      id: "bookingRequired",
      sectionId: "features",
      label: "Do you need booking or scheduling?",
      type: "select",
      required: true,
      options: [
        { label: "Yes", value: "yes" },
        { label: "No", value: "no" },
      ],
      prdMapping: ["features.booking"],
    },
    {
      id: "paymentsRequired",
      sectionId: "features",
      label: "Do you need payments?",
      type: "select",
      required: true,
      options: [
        { label: "Yes", value: "yes" },
        { label: "No", value: "no" },
      ],
      prdMapping: ["features.payments"],
      riskCategory: "commerce",
    },
    {
      id: "portalRequired",
      sectionId: "features",
      label: "Do you need a portal or member area?",
      type: "select",
      required: true,
      options: [
        { label: "Yes", value: "yes" },
        { label: "No", value: "no" },
      ],
      prdMapping: ["features.portal"],
    },
    {
      id: "bookingType",
      sectionId: "booking",
      label: "What kind of booking flow is needed?",
      type: "textarea",
      requiredWhen: { op: "equals", field: "bookingRequired", value: "yes" },
      visibleWhen: { op: "equals", field: "bookingRequired", value: "yes" },
      hiddenAnswerPolicy: "clear_when_hidden",
      prdMapping: ["booking.flow"],
    },
    {
      id: "calendarTool",
      sectionId: "booking",
      label: "Preferred calendar tool",
      type: "text",
      requiredWhen: { op: "equals", field: "bookingRequired", value: "yes" },
      visibleWhen: { op: "equals", field: "bookingRequired", value: "yes" },
      hiddenAnswerPolicy: "retain_when_hidden",
      prdMapping: ["booking.tool"],
    },
    {
      id: "paymentProvider",
      sectionId: "payments",
      label: "Preferred payment provider",
      type: "text",
      requiredWhen: { op: "equals", field: "paymentsRequired", value: "yes" },
      visibleWhen: { op: "equals", field: "paymentsRequired", value: "yes" },
      hiddenAnswerPolicy: "clear_when_hidden",
      prdMapping: ["payments.provider"],
    },
    {
      id: "paymentNeeds",
      sectionId: "payments",
      label: "Transaction, refund and reporting needs",
      type: "textarea",
      requiredWhen: { op: "equals", field: "paymentsRequired", value: "yes" },
      visibleWhen: { op: "equals", field: "paymentsRequired", value: "yes" },
      hiddenAnswerPolicy: "retain_for_audit",
      prdMapping: ["payments.needs"],
    },
    {
      id: "portalUsers",
      sectionId: "portal",
      label: "Who needs portal access?",
      type: "textarea",
      requiredWhen: { op: "equals", field: "portalRequired", value: "yes" },
      visibleWhen: { op: "equals", field: "portalRequired", value: "yes" },
      hiddenAnswerPolicy: "clear_when_hidden",
      prdMapping: ["portal.users"],
    },
    {
      id: "portalAuth",
      sectionId: "portal",
      label: "Authentication or role needs",
      type: "textarea",
      requiredWhen: { op: "equals", field: "portalRequired", value: "yes" },
      visibleWhen: { op: "equals", field: "portalRequired", value: "yes" },
      hiddenAnswerPolicy: "retain_when_hidden",
      prdMapping: ["portal.auth"],
    },
    {
      id: "integrationsNeeded",
      sectionId: "integrations",
      label: "Integrations required",
      type: "textarea",
      required: false,
      placeholder: "CRM, email marketing, analytics, API, internal tools.",
      prdMapping: ["integrations.required"],
      riskCategory: "integration",
    },
    {
      id: "seoImportant",
      sectionId: "seo",
      label: "Is SEO especially important?",
      type: "select",
      required: true,
      options: [
        { label: "Yes", value: "yes" },
        { label: "No", value: "no" },
      ],
      prdMapping: ["seo.importance"],
    },
    {
      id: "redirectsNeeded",
      sectionId: "seo",
      label: "Are redirects or migration support needed?",
      type: "textarea",
      requiredWhen: { op: "or", rules: [{ op: "equals", field: "websiteType", value: "redesign" }, { op: "equals", field: "websiteType", value: "migration" }] },
      visibleWhen: { op: "or", rules: [{ op: "equals", field: "websiteType", value: "redesign" }, { op: "equals", field: "websiteType", value: "migration" }] },
      hiddenAnswerPolicy: "retain_for_audit",
      prdMapping: ["seo.redirects"],
    },
    {
      id: "accessibilityLevel",
      sectionId: "compliance",
      label: "Accessibility target",
      type: "select",
      required: true,
      options: [
        { label: "WCAG AA", value: "wcag_aa" },
        { label: "WCAG AAA", value: "wcag_aaa" },
        { label: "Best effort", value: "best_effort" },
      ],
      prdMapping: ["compliance.accessibility"],
      riskCategory: "accessibility",
    },
    {
      id: "complianceNotes",
      sectionId: "compliance",
      label: "Compliance or privacy notes",
      type: "textarea",
      required: false,
      prdMapping: ["compliance.notes"],
    },
    {
      id: "launchDate",
      sectionId: "timeline",
      label: "Target launch date",
      type: "date",
      required: true,
      prdMapping: ["timeline.launch"],
    },
    {
      id: "budgetRange",
      sectionId: "timeline",
      label: "Budget range",
      type: "select",
      required: true,
      options: [
        { label: "Under $10k", value: "under_10k" },
        { label: "$10k - $25k", value: "10k_25k" },
        { label: "$25k - $50k", value: "25k_50k" },
        { label: "$50k+", value: "50k_plus" },
      ],
      prdMapping: ["timeline.budget"],
    },
    {
      id: "owner",
      sectionId: "timeline",
      label: "Primary owner or stakeholder",
      type: "text",
      required: true,
      prdMapping: ["timeline.owner"],
    },
    {
      id: "supportNeed",
      sectionId: "maintenance",
      label: "Post-launch support needs",
      type: "textarea",
      required: false,
      prdMapping: ["maintenance.support"],
    },
    {
      id: "notes",
      sectionId: "review",
      label: "Anything else we should know?",
      type: "textarea",
      required: false,
      prdMapping: ["review.notes"],
    },
  ],
};
